name: Build for Windows x64

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows-app:
    name: Release Windows x64
    runs-on: windows-latest
    steps:
      - name: 启用 Git 长路径支持
        run: git config --global core.longpaths true

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Apply Patch
        shell: pwsh
        run: |
          lib/scripts/patch.ps1 windows
          Set-Location $env:GITHUB_WORKSPACE

      - name: Set and Extract version
        shell: pwsh
        run: |
          lib/scripts/build.ps1
          Set-Location $env:GITHUB_WORKSPACE

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows Executable
        run: flutter build windows --release --dart-define-from-file=pili_release.json

      - name: Compress Portable Zip
        shell: pwsh
        run: |
          7z a -r PiliPlus_windows_portable.zip ./build/windows/x64/runner/Release/*

      - name: Upload windows file release
        uses: actions/upload-artifact@v4
        with:
          name: Windows-file-x64-release
          path: PiliPlus_windows_portable.zip
